### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by pariterre**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pariterre** [comment]
<code>@<space/>conda-forge-admin, please rerender</code>

**Comment by pariterre** [comment]
@conda-forge-admin, please rerender

**Comment by melund** [comment]
Hi @pariterre. I don't know why it fails right now and it is hard to check on my phone. I will try to take a closer look once I get to a real PC. I am on holiday this week. 

But please also add your self as a co maintainer of the recipe in the meta.yaml file. If you mind of course.

**Comment by pariterre** [comment]
It seems I don't have access to the logs... So I can't have a look :S

**Comment by pariterre** [comment]
I've tested this recipe on my computer and worked just fine. I assume this is because of the same problem discussed on the other PR? If so, we can accept and have a Mac version on Conda B-)

**Comment by pariterre** [comment]
Yep I just had a look on the previous PR and this is the same issue. 
It seems that these to PR can be accepted then! (I don't have write access to do it)
Thanks!

**Comment by melund** [comment]
You will have permissions to merge next time :)

**Pull request merged**
