### PR TITLE
Converted to new recipe format and update to v. 1.5.17

### PR DESCRIPTION
**Pull request by melund**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by melund** [comment]
@conda-forge-admin, please rerender

**Comment by melund** [comment]
@conda-forge-admin, please rerender

**Comment by melund** [comment]
Ok. I have to look into why `conda-recipe-manager` can't parse the new recipe. I know it fairly non-standard with the Octave stuff included. But I don't think that is only reason.

**Comment by pariterre** [comment]
Hi @melund 
Worst case, we can actually drop octave as I now push the matlab binaries directly with the releases. So octave builds are not necessary anymore, and is frankly confusing...
So if your suggestion is to remove it altogether, I agree!

**Comment by melund** [comment]
> worst case, we can actually drop octave as I now push the matlab binaries directly with the releases. 

Ahh cool. I will see if I can make something simpler :) 

I also saw that you pushed wheels to pypi. That is really cool, even though I still prefer speed of conda package and [pixi](https://pixi.sh)

**Comment by pariterre** [comment]
Yep! That was quite a journey, but a lot of people asked for it... I also prefer conda, but having both is useful haha!

**Comment by melund** [comment]
@conda-forge-admin, please rerender

**Comment by melund** [comment]
@pariterre. Now it works. Take a look and see if you think it is OK: I ended up removing Octave as you suggested.

**Pull request merged**
