### PR TITLE
Try to make win builds work

### PR DESCRIPTION
**Pull request by melund**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pariterre** [comment]
There is no need, Travis won't pass on Windows, according to conda. They told me if

**Comment by pariterre** [comment]
But having a nice checkmark is appreciated! Thanks for that :D

**Comment by melund** [comment]
> Errors on Windows can be ignored. They told me if AppVeyor passes then it is fine

Ok. Cool... I changed the compiler to [nmake jom](https://wiki.qt.io/Jom), so maybe you shouldn't merge this.

**Comment by pariterre** [comment]
I think more people uses Visual Studio. Since on Windows the compiler is important to what you bind with, I think I prefer to reject the PR and keep the Windows Travis not working
Thanks for the try though!

**Pull request closed without merging**
