### PR TITLE
DEP remove appveyor

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by pariterre** [comment]
I don't understand why it tries to link to python_d instead of python.. Is there anything I can do to help?

**Comment by beckermr** [comment]
I have no idea. Maybe someone on @conda-forge/core can help?

**Comment by pariterre** [comment]
Awesome :)
Anything else to do, or I should merge? :)

**Comment by beckermr** [comment]
OK. Merging. Thanks @isuruf !

**Pull request merged**
